import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const { name, email, phone, division, message } = await request.json();

    let nodemailer;
    try {
      // Bypassing Turbopack's static resolver using dynamic eval require
      const dynamicRequire = eval('require');
      nodemailer = dynamicRequire('nodemailer');
    } catch (e) {
      console.log("----- [MOCK EMAIL DISPATCHED (Nodemailer Not Installed)] -----");
      console.log("To: info.mahdev.lk@gmail.com");
      console.log("From Client Name:", name);
      console.log("Client Email:", email);
      console.log("Client Phone:", phone);
      console.log("Division Section:", division);
      console.log("Message Details:", message);
      console.log("-------------------------------------------------------------");
      return NextResponse.json({ 
        success: true, 
        mock: true, 
        message: "Nodemailer is not installed. Contact request logged to server console successfully." 
      });
    }

    // Use SMTP environment variables or fallback to a standard transporter
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.SMTP_USER || 'info.mahdev.lk@gmail.com',
        // In production, the user will configure their Gmail App Password as SMTP_PASS env variable
        pass: process.env.SMTP_PASS || 'mock_app_password_here'
      }
    });

    const mailOptions = {
      from: `"Mahdev Portal" <info.mahdev.lk@gmail.com>`,
      to: 'info.mahdev.lk@gmail.com',
      replyTo: email,
      subject: `New Contact Request: ${division} from ${name}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
          <h2 style="color: #dfba73; border-bottom: 2px solid #dfba73; padding-bottom: 10px; margin-top: 0;">New Contact Form Entry</h2>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; width: 150px; color: #555;">Name:</td>
              <td style="padding: 8px 0; color: #333;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Email:</td>
              <td style="padding: 8px 0; color: #333;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Phone:</td>
              <td style="padding: 8px 0; color: #333;"><a href="tel:${phone}">${phone}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Division:</td>
              <td style="padding: 8px 0; color: #dfba73; font-weight: bold;">${division}</td>
            </tr>
          </table>
          <div style="margin-top: 20px; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #dfba73; border-radius: 4px;">
            <strong style="color: #555; display: block; margin-bottom: 5px;">Client Message:</strong>
            <p style="margin: 0; color: #444; line-height: 1.6; font-style: italic;">"${message || 'No message provided.'}"</p>
          </div>
          <p style="font-size: 11px; color: #999; margin-top: 30px; text-align: center; border-top: 1px solid #eee; padding-top: 15px;">
            This email was auto-generated by the Mahdev Conglomerate Web Server.
          </p>
        </div>
      `
    };

    // If SMTP_PASS is mock or empty, log the email details in dev console to allow previewing
    if (!process.env.SMTP_PASS || process.env.SMTP_PASS === 'mock_app_password_here') {
      console.log("----- [MOCK EMAIL DISPATCHED] -----");
      console.log("To: info.mahdev.lk@gmail.com");
      console.log("Subject:", mailOptions.subject);
      console.log("Body Preview:", message);
      console.log("-----------------------------------");
      return NextResponse.json({ 
        success: true, 
        mock: true, 
        message: "Mock email logged to server console successfully. Setup your SMTP_PASS env variable to enable live delivery." 
      });
    }

    await transporter.sendMail(mailOptions);
    return NextResponse.json({ success: true, message: 'Email sent successfully!' });
  } catch (error) {
    console.error('Email dispatch error:', error);
    return NextResponse.json({ error: (error as Error).message }, { status: 500 });
  }
}
