import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const payload = await request.json();
    const { 
      name, email, phone, division, message, // inquiry fields
      date, location, packageName, specialRequests, divisionName, calculatedPrice, type // booking fields
    } = payload;

    const isBooking = type === 'booking' || !!packageName;
    const recipient = process.env.SMTP_TO || process.env.SMTP_USER || 'yuvanshan875@gmail.com';

    let nodemailer;
    try {
      // Dynamic require nodemailer to prevent bundler compilation errors
      const dynamicRequire = eval('require');
      nodemailer = dynamicRequire('nodemailer');
    } catch (e) {
      console.log("----- [MOCK EMAIL DISPATCHED (Nodemailer Not Installed)] -----");
      console.log("To:", recipient);
      console.log("Subject:", isBooking ? `Booking Request` : `Contact Request`);
      console.log("Payload:", JSON.stringify(payload, null, 2));
      console.log("-------------------------------------------------------------");
      return NextResponse.json({ 
        success: true, 
        mock: true, 
        message: "Nodemailer is not installed. Request logged to server console successfully." 
      });
    }

    // Configure the Nodemailer SMTP transporter using standard environment variables
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: false, // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER || 'info.mahdev.lk@gmail.com',
        pass: process.env.SMTP_PASS || ''
      },
      tls: {
        // Prevent connection drop due to local self-signed or unauthorized certificates on some environments
        rejectUnauthorized: false
      }
    });

    const subject = isBooking
      ? `New Booking Reservation: ${divisionName} (${packageName}) from ${name}`
      : `New Contact Request: ${division} from ${name}`;

    const htmlContent = isBooking
      ? `
        <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
          <h2 style="color: #D4AF37; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; margin-top: 0;">New Reservation Logged</h2>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; width: 150px; color: #555;">Client Name:</td>
              <td style="padding: 8px 0; color: #333;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Email:</td>
              <td style="padding: 8px 0; color: #333;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Phone:</td>
              <td style="padding: 8px 0; color: #333;"><a href="tel:${phone}">${phone}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Division Name:</td>
              <td style="padding: 8px 0; color: #333;">${divisionName}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Selected Package:</td>
              <td style="padding: 8px 0; color: #D4AF37; font-weight: bold;">${packageName}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Date Scheduled:</td>
              <td style="padding: 8px 0; color: #333;">${date}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Location / Venue:</td>
              <td style="padding: 8px 0; color: #333;">${location}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Estimated Cost:</td>
              <td style="padding: 8px 0; color: #D4AF37; font-weight: bold;">Rs. ${calculatedPrice?.toLocaleString() || '0'}</td>
            </tr>
          </table>
          <div style="margin-top: 20px; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #D4AF37; border-radius: 4px;">
            <strong style="color: #555; display: block; margin-bottom: 5px;">Special Requests:</strong>
            <p style="margin: 0; color: #444; line-height: 1.6; font-style: italic;">"${specialRequests || 'None provided.'}"</p>
          </div>
          <p style="font-size: 11px; color: #999; margin-top: 30px; text-align: center; border-top: 1px solid #eee; padding-top: 15px;">
            This email was auto-generated by the Mahdev Conglomerate Web Server.
          </p>
        </div>
      `
      : `
        <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
          <h2 style="color: #D4AF37; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; margin-top: 0;">New Contact Form Entry</h2>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; width: 150px; color: #555;">Name:</td>
              <td style="padding: 8px 0; color: #333;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Email:</td>
              <td style="padding: 8px 0; color: #333;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Phone:</td>
              <td style="padding: 8px 0; color: #333;"><a href="tel:${phone}">${phone}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #555;">Division:</td>
              <td style="padding: 8px 0; color: #D4AF37; font-weight: bold;">${division}</td>
            </tr>
          </table>
          <div style="margin-top: 20px; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #D4AF37; border-radius: 4px;">
            <strong style="color: #555; display: block; margin-bottom: 5px;">Client Message:</strong>
            <p style="margin: 0; color: #444; line-height: 1.6; font-style: italic;">"${message || 'No message provided.'}"</p>
          </div>
          <p style="font-size: 11px; color: #999; margin-top: 30px; text-align: center; border-top: 1px solid #eee; padding-top: 15px;">
            This email was auto-generated by the Mahdev Conglomerate Web Server.
          </p>
        </div>
      `;

    const mailOptions = {
      from: `"Mahdev Portal" <${process.env.SMTP_USER || 'info.mahdev.lk@gmail.com'}>`,
      to: recipient,
      replyTo: email,
      subject: subject,
      html: htmlContent
    };

    // If SMTP_PASS is not configured, fallback to mock console log in dev
    if (!process.env.SMTP_PASS) {
      console.log("----- [MOCK EMAIL DISPATCHED] -----");
      console.log("To:", mailOptions.to);
      console.log("From:", mailOptions.from);
      console.log("Subject:", mailOptions.subject);
      console.log("Body Preview:", isBooking ? packageName : message);
      console.log("-----------------------------------");
      return NextResponse.json({ 
        success: true, 
        mock: true, 
        message: "Mock email logged to server console successfully. Setup your SMTP_PASS env variable to enable live delivery." 
      });
    }

    await transporter.sendMail(mailOptions);
    return NextResponse.json({ success: true, message: 'Email sent successfully!' });
  } catch (error) {
    console.error('Email dispatch error:', error);
    return NextResponse.json({ error: (error as Error).message }, { status: 500 });
  }
}
